### ISSUE TITLE
Test one image_Operation error

### ISSUE THREAD

**Issue by 13sunmin** [princeton-vl/relative_depth#7]
Model file:../results/hourglass3/AMT_from_205315_1e-4_release/Best_model_period2.t7	
Processing sample img1.jpg	
/home/sunmin/torch/install/bin/luajit: /home/sunmin/torch/install/share/lua/5.1/nn/Container.lua:67: 
In 1 module of nn.Sequential:
/home/sunmin/torch/install/share/lua/5.1/cudnn/init.lua:145: Error in CuDNN: CUDNN_STATUS_ARCH_MISMATCH
stack traceback:
	[C]: in function 'error'
	/home/sunmin/torch/install/share/lua/5.1/cudnn/init.lua:145: in function 'getHandle'
	/home/sunmin/torch/install/share/lua/5.1/cudnn/init.lua:153: in function 'call'
	/home/sunmin/torch/install/share/lua/5.1/cudnn/init.lua:159: in function 'errcheck'
	/home/sunmin/torch/install/share/lua/5.1/cudnn/init.lua:174: in function 'toDescriptor'
	...torch/install/share/lua/5.1/cudnn/SpatialConvolution.lua:37: in function 'resetWeightDescriptors'
	...torch/install/share/lua/5.1/cudnn/SpatialConvolution.lua:96: in function 'checkInputChanged'
	...torch/install/share/lua/5.1/cudnn/SpatialConvolution.lua:120: in function 'createIODescriptors'
	...torch/install/share/lua/5.1/cudnn/SpatialConvolution.lua:188: in function <...torch/install/share/lua/5.1/cudnn/SpatialConvolution.lua:186>
	[C]: in function 'xpcall'
	/home/sunmin/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
	/home/sunmin/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
	test_on_one_image.lua:67: in main chunk
	[C]: in function 'dofile'
	...nmin/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50

WARNING: If you see a stack trace below, it doesn't point to the place where this error occurred. Please use only the one above.
stack traceback:
	[C]: in function 'error'
	/home/sunmin/torch/install/share/lua/5.1/nn/Container.lua:67: in function 'rethrowErrors'
	/home/sunmin/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
	test_on_one_image.lua:67: in main chunk
	[C]: in function 'dofile'
	...nmin/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50

How should I solve it？

**Comment by wfchen-umich** [comment]
Hi, this is likely a mismatch between your torch version and cudnn version as indicated by CUDNN_STATUS_ARCH_MISMATCH

**Comment by 13sunmin** [comment]
> Hi, this is likely a mismatch between your torch version and cudnn version as indicated by CUDNN_STATUS_ARCH_MISMATCH

I have torch7 (luajit) and cudnn5.1.
I see the online tutorial configuration, but other people don't have such problems

**Comment by 13sunmin** [comment]
> Hi, this is likely a mismatch between your torch version and cudnn version as indicated by CUDNN_STATUS_ARCH_MISMATCH

Can I remove cudnn in test on one image.lua

**Comment by 13sunmin** [comment]
> Hi, this is likely a mismatch between your torch version and cudnn version as indicated by CUDNN_STATUS_ARCH_MISMATCH

Can I remove cudnn in test on one image.lua
How can I do?

**Comment by wfchen-umich** [comment]
I don't think you can skip cudnn to make the code work. One suggestion is to make sure that your cudnn version matches that of cuda.

**Comment by 13sunmin** [comment]
> I don't think you can skip cudnn to make the code work. One suggestion is to make sure that your cudnn version matches that of cuda.

My GPU's computing power is 2.1, and what cudnn needs is 3.0. So there will be errors.
